### ISSUE TITLE
setValue of useLocalStorage should not change at each rerender

### ISSUE THREAD

**Issue by alex-kowalczyk** [juliencrn/usehooks-ts#118]
The `setValue` setter function returned by `useLocalStorage` is re-evaluated every time,
resulting in a lot of re-writes when it is specified as a dependency of an effect or callback (while skipping including it as dependency sometimes results in missing storage write). 

I suspect it should be wrapped in something like `useCallback(..., [setStoredValue])` to return a more "stable" object avoiding that issue.

**Comment by juliencrn** [comment]
Hi @alex-kowalczyk, good catch! Thanks for your feedback. I will fix it
