### ISSUE TITLE
How to use useInterval but have the callback runRight away then on a delay

### ISSUE THREAD

**Issue by Scalahansolo** [juliencrn/usehooks-ts#123]
Was looking through this lib and it looks awesome. In a project on my team, we have a version of the useInterval hook from Dan's blog post, but we made a small modification to it. We added the ability for the callback to be executed right away. 

```
function useInterval(callback, delay: number | null, runNow=false) {
  ...
  
  useEffect(() => {
    if (runNow && savedCallback.current) {
      savedCallback.current()
    } else return
  }, [runNow])
  
  ...
}
```

This has been useful for a handful of things. It seems like it would be generally useful, so I'm surprised that this isn't apart of the spec. But I'm guessing I'm just missing something simple with the useHooks-ts version to accomplish the same thing?

**Comment by juliencrn** [comment]
Hi @Scalahansolo, 
Thanks for your message, and sorry for the answer time... 
Indeed, you are able to reproduce this behavior passing `0` as delay. 
I will update the documentation to explain this useful possibility, thank you!
