### ISSUE TITLE
`setValue` should be referentially stable

### ISSUE THREAD

**Issue by jbean96** [juliencrn/usehooks-ts#132]
The `setValue` for `useLocalStorage` should be stored in a ref and a callback should be returned that invokes that ref i.e.

```
const setValueRef = useRef();

setValueRef.current = (value) => { ... } // existing logic goes here

const setValue = useCallback((value) => setValueRef.current?.(value), []);
```

This allows that `setValue` (like `setValue` returned from `useState` is referentially stable and does not need to be included as a dep in functions wrapped in `useCallback` that use this method.

**Comment by jbean96** [comment]
Note that this is related, but not the same as https://github.com/juliencrn/usehooks-ts/issues/118.

**Comment by jbean96** [comment]
I've created a PR to address this https://github.com/juliencrn/usehooks-ts/pull/133 

Although it should be considered a breaking change, I think it's a fine one to make as it makes the API of `useLocalStorage` more akin to that of `useState`.

**Comment by juliencrn** [comment]
Thank you, @jbean96, I've just approved your PR, I will publish it asap 🎉
