### ISSUE TITLE
Why useIsMounted hook return a function instead of react ref?

### ISSUE THREAD

**Issue by ZhaoTim** [juliencrn/usehooks-ts#134]
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/30540533/162136489-96378988-8ace-4b7b-b4d6-f088c6deb091.png">

Can anyone tell me? Why can't we just return isMounted.current and what is the purpose of using usecallback to wrap?

**Comment by juliencrn** [comment]
We just have preferred use `isMounted()` than `isMounted.current` as public API as you can see in the [`Usage section`](https://usehooks-ts.com/react-hook/use-is-mounted#usage).
