### ISSUE TITLE
Event bubbling

### ISSUE THREAD

**Issue by ddisimone** [juliencrn/usehooks-ts#141]
Hi :) 

What if i need an event bubbling ? 

`targetElement.addEventListener(eventName, eventListener, bubbling || false)
    return () => {
      targetElement.removeEventListener(eventName, eventListener, bubbling || false)
    }
  }, [eventName, element])`

**Comment by juliencrn** [comment]
We will support it soon, but while waiting, you can do that: https://codesandbox.io/s/usehooks-ts-react-component-template-forked-75ohbn?file=/src/App.tsx

**Comment by juliencrn** [comment]
Done in `2.6.0`
