### ISSUE TITLE
The example in useDarkMode() doesn't work

### ISSUE THREAD

**Issue by Chandler-Zhu** [juliencrn/usehooks-ts#146]
In the example of `useDarkMode()` hook, when I click the button, the text color and the background color doesn't change. Please fix it, preferably using tailwind classes

**Comment by proteriax** [comment]
`useDarkMode` just manages the state of dark mode, it doesn’t do the hard work of writing CSS for you. This is grossly out of scope.

**Comment by juliencrn** [comment]
thanks @proteriax
