### ISSUE TITLE
useEffectOnce never calls the cleanup function

### ISSUE THREAD

**Issue by jherr** [juliencrn/usehooks-ts#150]
With this change: https://github.com/juliencrn/usehooks-ts/issues/143 The `useEffectOnce` hook now no longer calls the cleanup function:

```ts
import { useState, useEffect } from "react";
import { useEffectOnce } from "usehooks-ts";

function SubComponent() {
  // This useEffect code works as expected, but in strict mode gets run twice
  // useEffect(() => {
  //   console.log("useEffect Mounted");
  //   return () => {
  //     console.log("useEffect Unmounted");
  //   };
  // });
  
  useEffectOnce(() => {
    console.log("useEffectOnce Mounted");
    return () => {
      // This never gets called
      console.log("useEffectOnce Unmounted");
    };
  });
  
  return <div>Hello</div>;
}

function App() {
  const [mounted, setMounted] = useState(true);
  return (
    <div>
      <button onClick={() => setMounted(false)}>Unmount</button>
      {mounted && <SubComponent />}
    </div>
  );
}
```

You can try this out live here:

https://codesandbox.io/s/angry-diffie-fj3ek6?file=/src/App.js

This fix comes from a blog post on AG-Grid that I think is also in error. That code assumes that the custom hook gets called to set `renderAfterCalled` to true, probably on the assumption that putting a `console.log` at that point will show it getting called twice, but it really doesn't get called twice, that second log is just `react-devtools`.

I actually have no idea about how to fix this the right way. There doesn't seem to be a way to detect strict mode, safely, externally to React.

**Comment by jherr** [comment]
Resolved with https://github.com/juliencrn/usehooks-ts/pull/152

**Comment by juliencrn** [comment]
Indeed, well done, thanks!

**Comment by runtothedoor** [comment]
> With this change: #143 The `useEffectOnce` hook now no longer calls the cleanup function:
> 
> ```ts
> import { useState, useEffect } from "react";
> import { useEffectOnce } from "usehooks-ts";
> 
> function SubComponent() {
>   // This useEffect code works as expected, but in strict mode gets run twice
>   // useEffect(() => {
>   //   console.log("useEffect Mounted");
>   //   return () => {
>   //     console.log("useEffect Unmounted");
>   //   };
>   // });
>   
>   useEffectOnce(() => {
>     console.log("useEffectOnce Mounted");
>     return () => {
>       // This never gets called
>       console.log("useEffectOnce Unmounted");
>     };
>   });
>   
>   return <div>Hello</div>;
> }
> 
> function App() {
>   const [mounted, setMounted] = useState(true);
>   return (
>     <div>
>       <button onClick={() => setMounted(false)}>Unmount</button>
>       {mounted && <SubComponent />}
>     </div>
>   );
> }
> ```
> 
> You can try this out live here:
> 
> https://codesandbox.io/s/angry-diffie-fj3ek6?file=/src/App.js
> 
> This fix comes from a blog post on AG-Grid that I think is also in error. That code assumes that the custom hook gets called to set `renderAfterCalled` to true, probably on the assumption that putting a `console.log` at that point will show it getting called twice, but it really doesn't get called twice, that second log is just `react-devtools`.
> 
> I actually have no idea about how to fix this the right way. There doesn't seem to be a way to detect strict mode, safely, externally to React.

I stopped to think and you are totally right @jherr. I would like a way to detect strict mode in a safe way but from what I've tried so far, things haven't worked so well. 

I believe that the cleanup function working is much more important than bypassing React.StrictMode

@juliencrn
