### ISSUE TITLE
Hydration Error with NextJS

### ISSUE THREAD

**Issue by sebahhpeya** [juliencrn/usehooks-ts#155]
Hi! I'm using the useMediaQuery hook and couse a hydration error with NextJS.

create a file  in `pages/hello.tsx`

```typescript
 import React from 'react'

import { useMediaQuery } from 'usehooks-ts'

export default function Component() {
  const matches = useMediaQuery('(min-width: 768px)')

  return (
    <div>
      {`The view port is ${matches ? 'at least' : 'less than'} 768 pixels wide`}
    </div>
  )
}
 ```

and i needed to do something like this: 

``` typescript
import React, { useEffect, useState } from 'react';

import { useMediaQuery } from 'usehooks-ts';

export default function Component() {
  const matches = useMediaQuery('(min-width: 768px)');
  const [str, setstr] = useState('');

  useEffect(() => {
    setstr(`The view port is ${matches ? 'at least' : 'less than'} 768 pixels wide`);
  }, [matches]);

  return <div>{str}</div>; 
```

If you check the console with the first example you can get an hydration error.

I could fixed the error with the second code example but it is just to share with you the issue.

Thanks for your work!

**Comment by juliencrn** [comment]
Hi @sebahhpeya, thanks for reporting an issue. I got it too, but I think it's not really a hook issue, but the normal behavior. Indeed, React doesn't know anything of the viewport on the server side. 

You could consider using `React.Suspense` for this kind of conditional display.

**Comment by johnmarcou** [comment]
I am not NextJS expert, but could that be related with this @juliencrn?

https://github.com/astoilkov/use-local-storage-state/issues/50#issuecomment-1123306107

**Comment by gregatgoogle** [comment]
@juliencrn, [MUI's `useMediaQuery` seems to implement some mechanisms to support SSR](https://github.com/mui/material-ui/blob/c987cfb8708c55c7616da0e98378451b7e12f893/packages/mui-material/src/useMediaQuery/useMediaQuery.ts).
Perhaps it's worth taking a look and utilising those ideas in usehooks-ts? IMO a two-pass rendering is better than having to remember not to useMediaQuery in SSR pages.

**Comment by xuanhung1509** [comment]
In my case, I got the problem solved by modifying the hook like this:

```tsx
import { useEffect, useState } from 'react'

// 1: Add null for return type
function useMediaQuery(query: string): boolean | null {
  // 2: Add this line
  const [matches, setMatches] = useState<boolean | null>(getMatches(query))

  const getMatches = (query: string): boolean => {
    // Prevents SSR issues
    if (typeof window !== 'undefined') {
      return window.matchMedia(query).matches
    }
    return false
  }

  // 3: Remove this line
  const [matches, setMatches] = useState<boolean>(getMatches(query))

  function handleChange() {
    setMatches(getMatches(query))
  }

  useEffect(() => {
    const matchMedia = window.matchMedia(query)

    // Triggered at the first client-side load and if query changes
    handleChange()

    // Listen matchMedia
    if (matchMedia.addListener) {
      matchMedia.addListener(handleChange)
    } else {
      matchMedia.addEventListener('change', handleChange)
    }

    return () => {
      if (matchMedia.removeListener) {
        matchMedia.removeListener(handleChange)
      } else {
        matchMedia.removeEventListener('change', handleChange)
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [query])

  return matches
}

export default useMediaQuery
```

Reference: https://observablehq.com/@werehamster/avoiding-hydration-mismatch-when-using-react-hooks

**Comment by octavioamu** [comment]
@xuanhung1509 you are missing something because that code will not work as you are referencing getMatches before declaration of the function

**Comment by yanalshoubaki** [comment]
@octavioamu  Thank you for your response, this code it's worked for me.
