### ISSUE TITLE
Improve useCountdown

### ISSUE THREAD

**Issue by PabloLION** [juliencrn/usehooks-ts#156]
Hi again @juliencrn, I just moved back to react. I'm thinking on improving the `useCountdown` hook. But there would be breaking changes so I want to firstly have a small discussion with you.

## Breaking changes

In the [example usage](https://usehooks-ts.com/react-hook/use-countdown)

```typescript
  const [count, { start, stop, reset }] = useCountdown({
    seconds: 60,
    interval: 500,
    isIncrement: false,
  })
```

1. (important) Rename `seconds` to `countNumber` or `startingCount`, `countStart`, etc. Since it is not the real seconds.
2. (trivial) Change `start`, `stop`, `reset` to `startCountdown`, `stopCountdown`, `resetCountdown` respectively. The default one would be unclear and make the code harder to maintain.
3. (trivial) Change `interval` to `intervalMs` or `intervalMilisec` specifying its unit.

## Non-breaking changes
1. Add a `countLimit`, or `limit`, `countdownLimit`, `countEnd`, etc. to the setting.

## Outcome & alternative

The final outcome of this proposal would look like this:

```typescript
  const [count, { startCountdown, stopCountdown, resetCountdown }] = useCountdown({
    countStart: 60,
    intervalMs: 1000, // add 1000 by default
    countStop: 0, // 0 by default
    isIncrement: false,
  })
```

Alternative is to make a new `useIntervalTimer` hook to do the same job but with new name.

Thanks for reading. What's your opinion?

**Comment by PabloLION** [comment]
Thanks for the confirmation. Working on it now.

> For the breaking change, it's ok, we will do minor update with a note in the changelog file 😎

On a second thought , maybe we can firstly keep the old functions and `console.warn()` about the deprecation when user uses the old ones, and then remove the old names in the next big version of usehooks-ts. What's your opinion?
Also, I'm thinking about using [@microsoft/tsdoc](https://www.npmjs.com/package/@microsoft/tsdoc) to add a `@deprecated` to make it clearer in VSCode, but there seem to be two problems:

1. I don't know where to add the TSDoc in this monorepo
2. Not sure if we can deprecate without changing the calling pattern.

I think you wouldn't mind me to ask the original creator @hexp1989 for his opinion on this too?

**Comment by juliencrn** [comment]
Slowly depreciate the old interface is really a good idea 👍  

I don't know if a package is needed to depreciate a function, adding a `@depreciated` JSDoc comment  and the `console.warn()` could be enough.

For the rest, try to keep the things as simple as possible, and we will see. You seem inspired, it's cool! Suit yourself 🤙

And yes, we need a staging v3 branch, I will create it.

**Comment by PabloLION** [comment]
> I don't know if a package is needed to depreciate a function, adding a `@depreciated` JSDoc comment and the `console.warn()` could be enough.

I didn't mean that package.. Its JSDoc improved to TSDoc, like JS - TS. You can just regard it as JSDoc.
I'll try to do the two versions and make 2 PRs. Thanks for the guidance. ❤️

**Comment by PabloLION** [comment]
Sorry that I'm having problem again... I tried to check the old solution https://github.com/juliencrn/usehooks-ts/issues/81#issuecomment-1015139681 but it has been changed, so I had to ask:

1. I cannot run `npm bootstrap`, and tried to diagnose with myself.
2. Cannot run `npm ci`
3. Cannot run `npm install`

<details>
<summary> Error of `npm install` </summary>
  
  ```
  npm ERR! code 126
  npm ERR! path ~/usehooks-ts/node_modules/lmdb-store
  npm ERR! command failed
  npm ERR! command sh -c node-gyp-build
  npm ERR! sh:~/usehooks-ts/node_modules/.bin/node-gyp-build: Permission denied
  ```

[2022-05-23T20_59_27_660Z-debug-0.log](https://github.com/juliencrn/usehooks-ts/files/8758049/2022-05-23T20_59_27_660Z-debug-0.log)

</details>

Can I get some help?

**Comment by juliencrn** [comment]
Have you tested to install from a fresh git clone? 
Are you using node@16 and npm@8?
Or maybe is there an issue with node-gyp-build, is this (https://github.com/kelektiv/node.bcrypt.js/issues/153) helping you?

The last `master` branch should work

**Comment by PabloLION** [comment]
I haven't tried with fresh clone. I'll try that later. 


I'm using node 18.2.0. I think there could be compatibility issue between note 14 and 16 but after 16 I don't see breaking changes So I assumed it was OK.  I also test that.

**Comment by hexp1989** [comment]
> Thanks for the confirmation. Working on it now.
> 
> > For the breaking change, it's ok, we will do minor update with a note in the changelog file 😎
> 
> On a second thought , maybe we can firstly keep the old functions and `console.warn()` about the deprecation when user uses the old ones, and then remove the old names in the next big version of usehooks-ts. What's your opinion? Also, I'm thinking about using [@microsoft/tsdoc](https://www.npmjs.com/package/@microsoft/tsdoc) to add a `@deprecated` to make it clearer in VSCode, but there seem to be two problems:
> 
> 1. I don't know where to add the TSDoc in this monorepo
> 2. Not sure if we can deprecate without changing the calling pattern.
> 
> I think you wouldn't mind me to ask the original creator @hexp1989 for his opinion on this too?

Hi PabloLION. Sorry to see this late.
The variable name's change is great. At first I was thinking of being more concise. So I added some jsdoc and use destructuring alias and make your own exact naming. But in typescript doesn't look good.
Your advice is great and I gladly accept. :)

**Comment by PabloLION** [comment]
it seems node 18 was the problem here. After having a new git clone, node18 still gives the same error, and with node16 everything worked fine

**Comment by PabloLION** [comment]
It seems that node@18 was the problem here. After having a new git clone, node@18 still gives the same error, and with node@16 everything worked fine. Also I tested with node@17 (not working). I'm changing the README file so it would be less misdirecting.

**Comment by PabloLION** [comment]
> And yes, we need a staging v3 branch, I will create it.

Nice call. Please create 🤣

**Comment by juliencrn** [comment]
V3 -> https://github.com/juliencrn/usehooks-ts/tree/v3 :)

**Comment by juliencrn** [comment]
Hi guys, now merged in master, it will be published soon (today). Thanks again 👏
