### ISSUE TITLE
The requested module 'usehooks-ts' is a CommonJS module, which may not support all module.exports as named exports.

### ISSUE THREAD

**Issue by ShravanSunder** [juliencrn/usehooks-ts#162]
Hi, i'm getting issues when i use a package that uses usehooks-ts as a dependency.  
- eth-hooks is a esm module with `type='module'`
- i'm trying to build a next js app
- here is the branch if you need it:  https://github.com/scaffold-eth/scaffold-eth-typescript/pull/91

I'm wondering if i need to have any settings?  i thought usehooks-ts was a esm module now?  @juliencrn

**Comment by ShravanSunder** [comment]
- maybe related to #97

**Comment by juliencrn** [comment]
Hi @ShravanSunder, thanks for reporting issue

Yes, current `usehooks-ts` should be ESM (as well as in the `eth-hooks` package, it should work.
And yes, it's related with #97 which we are working on.

**Comment by pencilcheck** [comment]
Still getting this error at 2.9.1
