### ISSUE TITLE
Listen event visibilitychange not found in useEventListener hooks

### ISSUE THREAD

**Issue by nguyenvannghi** [juliencrn/usehooks-ts#163]
Coding: 
```
 const onVisibilityTabChange = (event) => {
        if (document.hidden) {
            console.log('not visible')
        } else {
            console.log('is visible')
        }
    }

useEventListener('visibilitychange', onVisibilityTabChange)
```
Error: 
`Argument of type '"visibilitychange"' is not assignable to parameter of type 'keyof WindowEventMap'`

**Comment by juliencrn** [comment]
Good catch! Indeed, we support `WindowEventMap` and `HTMLElementEventMap` now, we will add `DocumentEventMap` as well. Thanks

**Comment by juliencrn** [comment]
We will support it soon, but while waiting, you can do that: https://codesandbox.io/s/usehooks-ts-react-component-template-forked-75ohbn?file=/src/App.tsx

**Comment by nguyenvannghi** [comment]
Cool

**Comment by juliencrn** [comment]
Done in `2.6.0`
