### ISSUE TITLE
useEventCallback not available in the documentation

### ISSUE THREAD

**Issue by fadhilx** [juliencrn/usehooks-ts#173]
in snippet/example below, it require `useEventCallback` hook, but not available on the docs;
https://usehooks-ts.com/react-hook/use-session-storage

it does exist in source file
https://github.com/juliencrn/usehooks-ts/blob/8f8c9850dd136dbc2e349048194e95b0877888a7/lib/src/useEventCallback/useEventCallback.ts

**Comment by juliencrn** [comment]
Hello, yes indeed, you're superfast, it was added yesterday 👏 

For now, it's just a private hook, but if you want to create the documentation page, it's welcome

**Comment by fadhilx** [comment]
oh, i didnt realized it at that time, what a coincidence, you add it right before i want to used it. thanks for the awesome repo

**Comment by mnelsonwhite** [comment]
Why not close this issue?
