### ISSUE TITLE
IntersectionObserverInit type

### ISSUE THREAD

**Issue by kg-currenxie** [juliencrn/usehooks-ts#186]
What's this? Seems missing

**Comment by juliencrn** [comment]
That's the native IntersectionObserver options like this

```ts
let options: IntersectionObserverInit = {
  root: document.querySelector('#scrollArea'),
  rootMargin: '0px',
  threshold: 1.0
}

let observer = new IntersectionObserver(callback, options);
```

https://usehooks-ts.com/react-hook/use-intersection-observer
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

**Comment by kg-currenxie** [comment]
Ok thanks :) I had the wrong TS version configured in my vscode
