### ISSUE TITLE
[Suggestion] useScript

### ISSUE THREAD

**Issue by curtvict** [juliencrn/usehooks-ts#203]
I'm curious if the community would find this change to the call signature of `useScript` at all useful:

```ts
function useScript(src: string, shouldLoad: boolean = true, removeOnUnmount: boolean = false): Status { ... }
```

`shouldLoad` could be used for something, like, an environment or privacy flag:

```ts
useScript('//some-script.js', isProduction) // or
useScript('//some-script.js', !isTest) // or
useScript('//some-script.js', user.isAnonymous)
```

`removeOnUnmount` could be used to remove the created script when the component calling `useScript` unmounts. Examples could be "one-shot" third party scripts that someone might just want to be present for a specific page of the app. Something like a HubSpot form that serves a specific use case, like Signing Up for an account.

If these sound like good ideas I'm happy to open a PR making the aforementioned changes.

**Comment by juliencrn** [comment]
Hi @curtvict, 
Yeah, it's a cool idea, I'll be happy to review your PR. 

What about a signature like this ?
```ts
interface UseScriptOptions {
  shouldLoad?: boolean
  removeOnUnmount?: boolean
}

useScript(src: string, options?: UseScriptOptions): Status { ... } 
```
