### ISSUE TITLE
useElementSize renders 3 times

### ISSUE THREAD

**Issue by Nishchit14** [juliencrn/usehooks-ts#205]
`useElementSize` is causing multiple re-rendering. It renders components three times at the first load.

**Comment by juliencrn** [comment]
Hi @Nishchit14, please could you create a minimal reproduction of your problem, by example in a [codesandbox](https://codesandbox.io/).

**Comment by carloscasalar** [comment]
You can see it using the react dev tools with the provided example code. 

Maybe the problem with this component is the self management of the ref. What about receiving the ref by parameter? With this approach maybe we could fix #196 as well. WDYT?

**Comment by juliencrn** [comment]
Hi, `useElementSize` has been deprecated and should be replaced by `useResizeObserver`.
