### ISSUE TITLE
Update React dependency to 18

### ISSUE THREAD

**Issue by herlon214** [juliencrn/usehooks-ts#210]
Hello, I moved to react 18 and would like to know if there's a chance of updating the React version here to 18 instead of 17.

I saw this PR https://github.com/juliencrn/usehooks-ts/pull/164 but it got closed and wasn't merged. Is there any reason?

I think this is the line that is causing the error:
https://github.com/juliencrn/usehooks-ts/blob/b87b0aa3e564f1e344603bb8f04550b561c67c2f/package.json#L66

The error my `npm i` is showing:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: bandsnear@0.1.1
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.9.0 || ^17.0.0" from usehooks-ts@2.7.0
npm ERR! node_modules/usehooks-ts
npm ERR!   usehooks-ts@"^2.6.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/herlon/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/herlon/.npm/_logs/2022-09-19T17_52_12_635Z-debug-0.log
 
```

**Comment by juliencrn** [comment]
Hi @herlon214, indeed we don't support yet react 18, we will soon. Thanks

**Comment by sharvit** [comment]
Thanks @juliencrn, Is there anything that should be done to support react v18?

* I could install the latest version on a react v18 project, and the few hooks I used worked fine
* I forked and updated to react v18, the tests and the build works fine, see: https://github.com/juliencrn/usehooks-ts/pull/214

**Comment by herlon214** [comment]
That's really nice @juliencrn, I will close the issue, thanks!

But unfortunately I already moved to another library =/
