### ISSUE TITLE
`useEventListener` with `CustomEvent` causes TS error

### ISSUE THREAD

**Issue by xegulon** [juliencrn/usehooks-ts#228]
When doing:

```ts
type MyEvent = 'upload:success' | keyof DocumentEventMap;

useEventListener<MyEvent>(
        'upload:success',
        (customEvent: CustomEvent<{ media: any[] }>) => {
            push(...customEvent.detail.media);
        },
        documentRef
    );
```

I get a TS2344 error: `cannot assign  'upload:success' to type keyof DocumentEventMap`

Although in the docs:

> Supports Window, Element and Document and __custom events__ with almost the same parameters as the native [addEventListener options](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#syntax). See examples below.

**Comment by juliencrn** [comment]
Hi @xegulon, you can declare the event to Typescript using: 

```ts
declare global {
  interface DocumentEventMap {
    'upload:success': CustomEvent<{ media: any[] }>
  }
}

...

useEventListener('upload:success', event => {
  console.log(event.detail.media) // No type error
}, documentRef)
```

**Comment by xegulon** [comment]
Thanks a lot! (could be great if it was added to the docs as an official way of doing things)
