### ISSUE TITLE
useReadLocalStorage should not always parse value as JSON

### ISSUE THREAD

**Issue by kevinxh** [juliencrn/usehooks-ts#240]
See https://github.com/juliencrn/usehooks-ts/blob/master/src/useReadLocalStorage/useReadLocalStorage.ts#L18, there is an incorrect assumption where the localstorage value is always JSON, but this is not true, you can have a string.

Assume you have the following item in your localstorage
| key | value |
|-----|-------|
|  customer_id   |  abcdefg     |

```
// this returns null
useReadLocalStorage('customer_id')
```

![Screen Shot 2022-10-17 at 10 13 52 PM](https://user-images.githubusercontent.com/10948652/196341171-af4c54fc-4e3a-4563-90a4-5d94f988e978.png)

### proposal

Treat localstorage values as type string, not JSON. Users can always do `Json.parse()` in the user land.

**Comment by kokosin4ik** [comment]
Same problem for the [useLocalStorage](https://usehooks-ts.com/react-hook/use-local-storage) hook

**Comment by juliencrn** [comment]
Thanks all 🙌

#439 should fix most of the points here.

Feel free to re-open the issue if needed
