### ISSUE TITLE
useSSR isn't a custom hook

### ISSUE THREAD

**Issue by pedrobslisboa** [juliencrn/usehooks-ts#258]
Custom hooks must contain at least one hook inside them to become a valid hook. Unfortunately, we only have an SSR utility called "hook," which can give users a false idea about custom hooks and incentivize bad coding practices.

```ts
Copy code
function useSsr() {
  const isDOM =
    typeof window !== 'undefined' &&
    window.document &&
    window.document.documentElement

  return {
    isBrowser: isDOM,
    isServer: !isDOM,
  }
}
```

As we can see, useSsr does not contain any hook inside it.

References:
https://reactjs.org/docs/hooks-custom.html#:~:text=A%20custom%20Hook%20is%20a%20JavaScript%20function%20whose%20name%20starts%20with%20%E2%80%9Duse%E2%80%9D%20and%20that%20may%20call%20other%20Hooks
https://www.robinwieruch.de/react-custom-hook/#:~:text=Therefore%20a%20custom%20Hook%20is%20always%20a%20new%20composition%20of%20one%20or%20multiple%20Hooks.%20If%20a%20custom%20Hook%20does%20not%20use%20any%20hooks%20internally%2C%20it's%20not%20a%20custom%20Hook%20and%20shouldn't%20have%20the%20prefix%20%22use%22.

**Comment by pedrobslisboa** [comment]
@juliencrn

**Comment by mlshv** [comment]
There's also a problem with this function. You can't really use it because it will produce hydration error: the first client render wouldn't match server render. To make this function a hook and to make it work one should perform the check in `useEffect` and set the result in state.

**Comment by juliencrn** [comment]
Good catch @pedrobslisboa, it is now depreciated and will be removed in the next major version
