### ISSUE TITLE
Can I use this library in a Next.js project?

### ISSUE THREAD

**Issue by Teiger212** [juliencrn/usehooks-ts#264]
Next v.12 uses 14.17.0 (currently)
usehooks-ts requires >=16.15.0

Is there a solution?
TIA

**Comment by sinamoradi1375** [comment]
> Next v.12 uses 14.17.0 (currently) usehooks-ts requires >=16.15.0
> 
> Is there a solution? TIA
Hi, I'm currently using Next v12.2.0 and node v16.15.0, and everything's working fine. What seems to be the problem you're having?
