### ISSUE TITLE
The `useFetch()` hook is hardcoded to work only with JSON

### ISSUE THREAD

**Issue by haroldo-ok** [juliencrn/usehooks-ts#266]
If I try to use `useFetch()` on some API endpoint that returns plain text or an image, it returns an error because `useFetch()` is hardcoded to parse the response body as JSON.

**Comment by juliencrn** [comment]
Hi, thanks for the bug report! 

I'll close the issue because `useFetch` will be deprecated and then dropped. 
Instead, I suggest you to use either:
- Your framework stuff (like RSC or getServerSideProps from NextJS for example)
- `use` from React
- Libraries like `react-query` or `useSWR`

**Comment by DerGoogler** [comment]
@haroldo-ok @figurluk 

Use this: https://github.com/DerGoogler/MMRL/blob/master/Website/src/hooks/useFetch.ts

```js
const [mData, mError] = useFetch("url", { type: "text" })
```
> Default is `json`
