### ISSUE TITLE
Cannot find module 'usehooks-ts'

### ISSUE THREAD

**Issue by xencodes** [juliencrn/usehooks-ts#267]
I recently installed `usehooks-ts` in a React TypeScript (Vite)  project, but it is showing types error.

`Cannot find module 'usehooks-ts' or its corresponding type declarations.ts(2307)`

Can anyone tell me how to fix this issue?

**Comment by ObaidQatan** [comment]
was this issue solved?

**Comment by laurentlahmy** [comment]
I have the issue, not sure why
