### ISSUE TITLE
useEventCallback exported but not documented

### ISSUE THREAD

**Issue by CroModder** [juliencrn/usehooks-ts#281]
useEventCallback is exported (https://github.com/juliencrn/usehooks-ts/blob/master/src/index.ts#L21-L22) but there is no clue about it in the docs. Don't know if it's exported by mistake and should be used only internally or it's just missing from the docs.

**Comment by juliencrn** [comment]
Good catch, it's an internal hook indeed, it shouldn't be exported from the index 👍
