### ISSUE TITLE
"Workspaces can only be enabled in private projects."

### ISSUE THREAD

**Issue by jherdman** [juliencrn/usehooks-ts#294]
Usage of this project results in the following warning being issued during `yarn install`:

```
Workspaces can only be enabled in private projects.
```

I believe this can be resolved by eliminating the usage of workspaces entirely, or reorganizing the project as a proper monorepo. The former is likely easier as you're only including a single custom eslint ruleset which could just be merged into the main eslint ruleset.

**Comment by juliencrn** [comment]
Thanks for the feedback, we opted for Turborepo witth pnpm workspaces 👍
