### ISSUE TITLE
useLocalStorage's value doesn't change when the key changes

### ISSUE THREAD

**Issue by shoooe** [juliencrn/usehooks-ts#296]
In an example like [this one](https://codesandbox.io/embed/usehooks-ts-react-component-template-forked-7y483g?fontsize=14&hidenavigation=1&theme=dark):

```typescript
import { useEffect } from "react";
import { useCountdown, useLocalStorage } from "usehooks-ts";

export default function Component() {
  const [count, { startCountdown }] = useCountdown({
    countStart: 1000,
    intervalMs: 1000
  });
  useEffect(startCountdown, [startCountdown]);

  const key = `darkTheme${count}`;
  const defaultValue = count % 2 === 0;
  // Even if the `key` and `defaultValue` change every second,
  // `isDarkTheme` remains alsways the initial value.
  console.log(key, defaultValue);
  const [isDarkTheme, setDarkTheme] = useLocalStorage(key, defaultValue);

  const toggleTheme = () => {
    setDarkTheme((prevValue: boolean) => !prevValue);
  };

  return (
    <button onClick={toggleTheme}>
      {`THEME = ${isDarkTheme ? `DARK` : `LIGHT`}`}
    </button>
  );
}
```

I would expect `isDarkTheme` to change every second because the `key` and default value changes every second. Instead it remains the same value. This seems like a bug.
Shouldn't a change in `key` refetch the default value (or the existing value if it's already there)?
Am I missing something?

Thanks 🙏

**Comment by cdaycmc** [comment]
Found a work around where you can force a re-render by passing in a different key
```
const LocalStorage = (lsKey, initValue) => {
   const [value, setValue] = useLocalStorage(lsKey, initValue);
  ....
}

const Higher = () => {
  const lsKey = /* something that changes */
  ...
  {/* pass lsKey as key to component to force unmount/mount cycle when it changes */}
  <LocalStorage key={lsKey} lsKey={lsKey} />
  ...
}
```

Proper fix is to capture the key inside useState inside the hook then compare it to key passed in and if it changes to read localstorage and update internal value state

**Comment by wayneschuller** [comment]
I think I am stuck on the same problem...

**Comment by juliencrn** [comment]
Hi all, these changes should fix almost all problems here:
- #298
- #355

Thanks for the feedback 👍
