### ISSUE TITLE
useLocalStorage - storing objects causes unnecessary re-renders

### ISSUE THREAD

**Issue by tsnevillecom** [juliencrn/usehooks-ts#306]
Due to Javascript's object reference inequality... I found I needed to do a deep comparison on stored values.

I changed:

`const [storedValue, setStoredValue] = useState<T>(readValue)`

to

```
  const [storedValue, _setStoredValue] = useState<T>(readValue)

  const setStoredValue = (newState: T) => {
    _setStoredValue((prev) => {
      if (JSON.stringify(newState) !== JSON.stringify(prev)) {
        return newState
      } else {
        return prev
      }
    })
  }
  ```

Using lodash also works well.

```
  const [storedValue, _setStoredValue] = useState<T>(readValue)

  const setStoredValue = (newState: T) => {
    _setStoredValue((prev) => {
      if (!_.isEqual(newState, prev)) {
        return newState
      } else {
        return prev
      }
    })
  }
  ```

**Comment by MickaelNeves** [comment]
unfortunately, these won't stop re-renders

**Comment by juliencrn** [comment]
The hook has been updated recently, I'll close this issue for inactivity. Feel free to re-open it if the problem persists on the latest version of `usehooks-ts`. Thanks
