### ISSUE TITLE
useScript cleanup on removeOnUnmount

### ISSUE THREAD

**Issue by sebadom** [juliencrn/usehooks-ts#314]
I'm using useScript in an nextjs app, to load an external javascript snippet that runs it's initialization logic on load, therefore whenever I navigate to another page I'm using `removeOnUnmount` in true, with the hope that any further navigation to any other page using this widget will re init everything. Now the thing is I've seen the code and while it disables the listeners and remove the node, it doesn't actually remove the cached key from `cachedScriptStatuses` therefor it does not recreate the node again. 

Is that a bug or is that by design?

Thank you

**Comment by ShanSenanayake** [comment]
I have run into the same issue and is also wondering about the same thing. 
The cached script isn't remove as a key which means if we want to mount the component again it assumes the script is already loaded, which is not the case when `removeOnUnmount` is set to true. I would assume this is a bug.

**Comment by juliencrn** [comment]
Hi, thanks for the feedback, it has been fixed in #354 and will be released in days
