### ISSUE TITLE
useElementSize does not detect resize of element, only resize of browser

### ISSUE THREAD

**Issue by quinn** [juliencrn/usehooks-ts#325]
https://github.com/juliencrn/usehooks-ts/blob/master/src/useElementSize/useElementSize.ts#L33

^^^^ I'm assuming without a 3rd arg, it binds to window? Why isn't the ref for the element passed in as the 3rd arg?

**Comment by AndreaPontrandolfo** [comment]
Can confirm. It seem to detect the sizes of the element only on the first try, then it's always 0.
