### ISSUE TITLE
useCopyToClipboard unnecessarily rerenders 'copy' function every time

### ISSUE THREAD

**Issue by nmacianx** [juliencrn/usehooks-ts#357]
The `copy` function returned by the `useCopyToClipboard` is recreated every time, which makes hooks using the `copy` function as a dependency rerender every time.
In my case, a `useMemo` hook is unnecessarily changing due to a dependency function that was using the `copy` function, introducing undesired behavior to the app.

It's a very easy fix to the hook. I'm about to open a PR with the fix

**Comment by juliencrn** [comment]
Thanks  @nmacianx, it'll be in the next release, probably `2.9.6`

**Comment by nmacianx** [comment]
You're welcome @juliencrn! Happy to help
