### ISSUE TITLE
`useLocalStorage` produce different state for server and client rendering

### ISSUE THREAD

**Issue by moshest** [juliencrn/usehooks-ts#369]
When using `useLocalStorage` it loads the local storage immediately if the `window` exists and fallback to the default value on server side. This produce inconsistency when rendering code in SSR as the server and client code do not match!

Instead, the first render should always be from the default value and only later when `useEffect` called it will update the state to the local storage value correctly.

The same apply for `useSessionStorage`.

**Comment by MarlonPassos-git** [comment]
@moshest 

This could actually be a problem. 
however, I see that there will be situations where the person will want the value to be from the local storage from the beginning (not all projects use SSR). 

Do you think that having a `useInitialValues` prop (or similar) would be a good solution? 

Anything I can be working on something

**Comment by moshest** [comment]
It's not a question of preference. Using this hook in it's currently configuration will produce a warning from React. The current implementation is not following the React guidelines and break the UI for SSR rendering.

**Comment by julianCast** [comment]
> @moshest
> 
> This could actually be a problem. however, I see that there will be situations where the person will want the value to be from the local storage from the beginning (not all projects use SSR).
> 
> Do you think that having a `useInitialValues` prop (or similar) would be a good solution?
> 
> Anything I can be working on something

Yes, I'm facing the same issue. Here is the solution provided by a similar library in case is useful where they use an initialValue. They are SSR compatible.

https://react-hookz.github.io/web/?path=/docs/side-effect-uselocalstoragevalue--example

[Github useLocalStorageValue from react-hookz](https://github.com/react-hookz/web/tree/c1288f21475c91ce522158d39900598eac38fb39/src/useLocalStorageValue)

**Comment by juliencrn** [comment]
Should have been fixed by #435, will be in the next release. Thanks all!
