### ISSUE TITLE
[Discussion] Is usehooks-ts still maintained?

### ISSUE THREAD

**Issue by rrmesquita** [juliencrn/usehooks-ts#373]
Just "reopening" [#323](https://github.com/juliencrn/usehooks-ts/issues/323) as @juliencrn simply closed it and didn't provide any details whatsoever.

From what I understand, Julien is busy with other opportunities and doesn't have the time or is not interested anymore in maintaining this library. And that is totally fine, really, but as I write this, [usehooks-ts](https://www.npmjs.com/package/usehooks-ts) has +330K weekly downloads, which makes it one of the most popular hooks package for React. The community wants to contribute to this awesome package, so we ask to elect some other person to continue the work of reviewing and publishing these contributions.

Thanks!

**Comment by yungjurick** [comment]
Also support the need for more maintainers!

**Comment by vsnthdev** [comment]
Yup, I have also previously tried to contribute to this library with no luck!

**Comment by juliencrn** [comment]
Hey everyone, your support has been rad! Missed hacking on usehooks-ts, but I'm stoked to get back in January. Time for some fresh vibes and goals, like reviving this project!

Initially, I'll focus on rekindling the project and reviewing each opened issue and PR. Afterward, I'll explore solutions for long-term support. Thanks for being part of this journey! 😊🚀

**Comment by naquiroz** [comment]
Hi @juliencrn are you still maintaining it?
