### ISSUE TITLE
🔧[`gen-hook` tooling issue] Trying to use gen-hook gives ERROR Unable to run generate - missing requirements (npx)

### ISSUE THREAD

**Issue by DarkAng3L** [juliencrn/usehooks-ts#381]
On Windows PC ,with `pnpm@8.7.5`, when trying to run `pnpm gen-hook` command, I receive the following error in the console:
```shell
& pnpm -v
8.7.5

$ pnpm gen-hook

> workspace@ gen-hook C:\Users\DarkAngel\PhpstormProjects\usehooks-ts
> turbo gen hook && pnpm format

ERROR Unable to run generate - missing requirements (npx)
 ELIFECYCLE  Command failed with exit code 1.
```

Note: This issue seems to be fixed in an updated version of `turbo@1.10.2`: https://github.com/vercel/turbo/issues/5075

**Comment by juliencrn** [comment]
Thanks for the report! 

Both `turbo` and `@turbo/gen` have been upgraded to the latest. 
The issue should be fixed. I'll close it but feel free to re-open it if the problem persists.
