### ISSUE TITLE
bug: `useIsFirstRender` broken with NextJs App router

### ISSUE THREAD

**Issue by technophile-04** [juliencrn/usehooks-ts#389]
### Demo : 

It seems that `useIsFirstRender` always returns `false` in NextJs App router, here is an example : 

https://github.com/juliencrn/usehooks-ts/assets/80153681/4e35aaa8-6a0f-4a03-89ab-7d011ccc49f8

So `localhost:8080` serves the page from `app` dir and `localhost:8080/pagedir` serves it from `pages` dir 

As we can see when on `localhost:8080`  `useUpdateEffect` runs directly instead on `localhost:8080/pagedir` it does not since its it first render 

here is minimal reproducible repo : https://github.com/technophile-04/useIsFirstRender-mrr

Its just a new create-next-app with `usehooks-ts` installed and utilizing `useDarkMode` which internally rely's on `useIsFirstRender`

---

### Possible reason : 

Maybe it's because Nextjs might be running `useIsFirstRender` in server before serving it to client, saying this because I came across this https://github.com/vercel/next.js/issues/52566#issuecomment-1631546536 which states some hooks can be ran on server like `useId` etc and `useRef` might be one of them 🤔 but I maybe completely wrong here !! 

### Update :
 It seems that disabling `reactStrictMode` in `App router` solves the issue but its bad idea  to do so :(

**Comment by juliencrn** [comment]
`useDarkMode` is no longer based  on `useIsFirstRender`, this should be fixed right now
