### ISSUE TITLE
Typo on Documentation Page https://usehooks-ts.com/react-hook/use-copy-to-clipboard

### ISSUE THREAD

**Issue by andyjphu** [juliencrn/usehooks-ts#398]
I'm fairly new to react hooks and the copy method, but I'm assuming there's a typo in 

> This React hook provides a copy method to save a string **in the and the** copied value (default: null).

I wasn't sure where to submit this, so let me know if this was the wrong place.

**Comment by juliencrn** [comment]
Good catch! 

The `Link` component was broken.

> This React hook provides a copy method to save a string in the `<a></a>` and the copied value (default: null).
