### ISSUE TITLE
Grammar Correction Suggestion in Documentation for use-intersection-observer

### ISSUE THREAD

**Issue by ingadi** [juliencrn/usehooks-ts#399]
In the page [use-intersection-observer](https://usehooks-ts.com/react-hook/use-intersection-observer), I encountered the following sentence:

"I discovered this way of using IntersectionObserver via this while playing to build a ."

The sentence seems to lack proper completion, and it might benefit from a clarification or correction for better understanding by users.

**Comment by juliencrn** [comment]
![Screenshot 2024-01-20 at 00 57 19](https://github.com/juliencrn/usehooks-ts/assets/14028029/aa0e0e51-33a7-4adc-a970-39eb004a0a3c)

There was an issue with the link component, now fixed. Thanks for the report
