### ISSUE TITLE
Suggestion for improvements to docs for useSessionStorage and useLocalStorage hooks

### ISSUE THREAD

**Issue by dandubya** [juliencrn/usehooks-ts#401]
The documentation for both `useSessionStorage` and `useLocalStorage` read almost exactly the same:
    ```
    Persist the state with local storage so that it remains after a page refresh. ..
    ```
    ```
    Persist the state with session storage so that it remains after a page refresh. ...
    ```

For experts, the difference between `useSessionStorage` and `useLocalStorage` is probably obvious. For newbs, it could be valuable to clarify. 

In particular, if I have the same page open in multiple tabs, when I use `useLocalStorage`, both tabs will have the same persisted state. If I make a change in one, that saved state is now available to the other.  If I close the browser/tab and reopen the page, the saved state is still available to it.

When I use `useSessionStorage`, OTOH, there are no side effects between tabs - i.e., they remain independent. If I close the browser/tab and reopen the page, the saved state is no longer available to it.

Perhaps there are other important differences I haven't yet encountered that could also be added to the docs?

**Comment by juliencrn** [comment]
Thank you for pointing that out! You're absolutely right. We've now included direct links to the MDN references to give users more clarity on how these hooks work with web APIs.


![Screenshot 2024-03-28 at 14 18 04](https://github.com/juliencrn/usehooks-ts/assets/14028029/db1daab2-ffd3-4204-a8fe-5a601c2410ce)
<img width="1433" alt="Screenshot 2024-03-28 at 10 09 56" src="https://github.com/juliencrn/usehooks-ts/assets/14028029/65588f4a-67c3-4887-95a8-372c0e02746a">

**Comment by juliencrn** [comment]
@all-contributors please add @dandubya for doc
