### ISSUE TITLE
addListener is deprecated

### ISSUE THREAD

**Issue by VenomFate-619** [juliencrn/usehooks-ts#402]
In useMediaQuery  hook, there is a method used named addListener.

```javascript
    if (matchMedia.addListener) {
      matchMedia.addListener(handleChange)
    } else {
      matchMedia.addEventListener('change', handleChange)
    }
``` 
In the above code, addListener is deprecated [link](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener)

May we change to **resize**  event listener

**Comment by juliencrn** [comment]
Hi, you're right but we will keep it to support Safari < 14 (2020). See #135 Thanks for the feedback!
