### ISSUE TITLE
v2.9.2 was never published

### ISSUE THREAD

**Issue by mariusGundersen** [juliencrn/usehooks-ts#404]
It seems like v2.9.2 was never published to npm. It would be great to have this version, since it exposes the esm modules properly

**Comment by juliencrn** [comment]
It's deployed

**Comment by juliencrn** [comment]
@mariusGundersen #391 will be in the v3, I'm looking forward too ;)

**Comment by sigma-andex** [comment]
How about dropping CommonJS alltogether? Apparently the concurrent CommonJS and ESM support is causing many issues for many people. It's 2024, all browsers support ESM modules.

**Comment by juliencrn** [comment]
Hi @sigma-andex, 
I agree with you but some people seem to still want `commonjs`. 
However, the v3 will probably move `usehooks-ts` as an ESM-first package with CJS support, it looks like easy using tools like `tsup` and the `exports` property in `package.json`.
I've already done some tests, it seems to be working. 

I just want to process opened issues/PRs before batching all breaking changes together in the major release
