### ISSUE TITLE
🔴 [BUG REPORT] Version 2.9.3 is entirely empty

### ISSUE THREAD

**Issue by satelllte** [juliencrn/usehooks-ts#422]
## Issue

Version `2.9.3` published 1 hour ago: https://www.npmjs.com/package/usehooks-ts?activeTab=versions
and it's fully empty: https://bundlephobia.com/package/usehooks-ts@2.9.3

## How to reproduce

```
❯ npm install usehooks-ts@latest
❯ ls ./node_modules/usehooks-ts 
LICENSE		README.md	package.json
```

---

**P.S.** I can't log a "bug report" issue due to https://github.com/juliencrn/usehooks-ts/pull/421, so logging it under "documentation" for now

**Comment by juliencrn** [comment]
OMG, I forgot to rebuild the package 🤦‍♂️ It was fixed in 2.9.4
