### ISSUE TITLE
[BUG] LocalStorage is not immediately accessible.

### ISSUE THREAD

**Issue by beefiker** [juliencrn/usehooks-ts#444]
### Describe the bug

It was fine when using version 2.9.5, but error occurs in version 2.10.0 (latest one)

in version 2.9.5, there is no `deserializer`, it works fine without delay.
but in the latest version 2.10.0, there is `deserializer` wrapped with `useCallback`.

so, we can't get localStorage value immediately.

[You can check this bug right here](https://codesandbox.io/p/devbox/usehooks-ts-err-y2wmpy?file=%2Fapp%2Fuser%2Fpage.tsx%3A1%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clru5un4c00073b6hobinpirx%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clru5un4c00023b6hvs4yw73m%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clru5un4c00043b6hly8pvrtv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clru5un4c00063b6h9bfecmd7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clru5un4c00023b6hvs4yw73m%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clru5un4c00013b6hr5mn8du2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clru5w0xm00023b6hutn3gv3v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A26%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A26%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrum6b4800023b6hgpo4zwrn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A1%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Fuser%252Fpage.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clru5un4c00023b6hvs4yw73m%2522%252C%2522activeTabId%2522%253A%2522clrum6b4800023b6hgpo4zwrn%2522%257D%252C%2522clru5un4c00063b6h9bfecmd7%2522%253A%257B%2522id%2522%253A%2522clru5un4c00063b6h9bfecmd7%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clru5un4c00053b6h1cr7nq9s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clru5un4c00053b6h1cr7nq9s%2522%257D%252C%2522clru5un4c00043b6hly8pvrtv%2522%253A%257B%2522id%2522%253A%2522clru5un4c00043b6hly8pvrtv%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clru5un4c00033b6hxrxz6i8o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clru5un4c00033b6hxrxz6i8o%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### To Reproduce

in version 2.10.0

### Expected behavior

There should be no delay when reading value from LocalStorage.

**Comment by juliencrn** [comment]
HI, thanks for the bug report. 
We have updated the API to make it SSR-friendly, so you'll be able to use it as previously. See #451
It will be released this week
