### ISSUE TITLE
hook "useUnmount" is in the documentation but not included in the package when installed via npm

### ISSUE THREAD

**Issue by retnag** [juliencrn/usehooks-ts#449]
### Describe the problem

As stated in the title, the hook and its source files/folders are missing.
I have confirmed the version installed from the package.json inside `node_modules/usehooks-ts` to be 2.10.0.
Either the docs or the code is wrong, maybe, this is a future feature, and should be denoted as such in the docs? https://usehooks-ts.com/react-hook/use-unmount

**Comment by papalardo** [comment]
same with *useDebounceCallback*

**Comment by juliencrn** [comment]
Oups 😅 Deployed the docs too fast, before the package release 🤦‍♂️. 
Will release asap! Thanks for the feedback 👍
