### ISSUE TITLE
[BUG] Can't resolve `lodash.debounce`

### ISSUE THREAD

**Issue by eleazareramos** [juliencrn/usehooks-ts#453]
### Describe the bug

Latest version `2.11.0` introduced this build error:

```
Failed to compile.
--
19:16:17.545 |  
19:16:17.545 | ./node_modules/usehooks-ts/dist/esm/useDebounceCallback/useDebounceCallback.js
19:16:17.545 | Module not found: Can't resolve 'lodash.debounce'
19:16:17.545 |  
19:16:17.545 | https://nextjs.org/docs/messages/module-not-found
19:16:17.545 |  
19:16:17.545 | Import trace for requested module:
19:16:17.545 | ./node_modules/usehooks-ts/dist/esm/useDebounceCallback/index.js
19:16:17.545 | ./node_modules/usehooks-ts/dist/esm/index.js
```

### To Reproduce

Build error occurred on a NextJS app at version `13.5.2` during deployment to Vercel.
I also have `lodash` in my `package.json` at version `4.17.21`

### Expected behavior

`lodash.debounce` module to be resolved

**Comment by juliencrn** [comment]
Hi, `lodash.debounce` is a usehooks' optional peer dependency required in `useDebounceCallback`. You need to `npm i lodash.debounce` to use this hook. It was added that way to minimize the bundle size, only pay for what you use.

However, it could be interesting to fall back to `lodash` if `lodash.debounce` is not available, idk if it's possible.
