### ISSUE TITLE
[BUG] useSessionStorage @2.11.0

### ISSUE THREAD

**Issue by Hyodori04** [juliencrn/usehooks-ts#456]
### Describe the bug

useSessionStorage return undefined when server side, And it makes TypeError: Cannot read properties of undefined. I want to use default value in server side

### To Reproduce

use useSessionStorage in next.js with defaultValue

### Expected behavior

defaultValue should be exists . It should not to be undefined

**Comment by Hyodori04** [comment]
```
// Get from session storage then
  // parse stored json or return initialValue
  const readValue = useCallback((): T => {
    const initialValueToUse =
      initialValue instanceof Function ? initialValue() : initialValue

    // Prevent build error "window is undefined" but keep keep working
    if (IS_SERVER) {
      return initialValueToUse
    }

    try {
      const raw = window.sessionStorage.getItem(key)
      return raw ? deserializer(raw) : initialValueToUse
    } catch (error) {
      console.warn(`Error reading sessionStorage key “${key}”:`, error)
      return initialValueToUse
    }
  }, [initialValue, key, deserializer])

  const [storedValue, setStoredValue] = useState(() => {
    if (initializeWithValue) {
      return readValue()
    }
    return undefined
  })
```


because initializeWithValue is always false in server. It return undefined
but readValue function handle server with default value. I think it's not meaned to in server always return undefined

**Comment by juliencrn** [comment]
#472 should fix it, thanks for bug report :)
