### ISSUE TITLE
[BUG] Missing modules whie using with Next.js

### ISSUE THREAD

**Issue by BlankParticle** [juliencrn/usehooks-ts#458]
### Describe the bug

I am trying to use `useInterval` hook with Next.js App router, and I am getting a error `Module not found: Can't resolve 'lodash.debounce'` while trying to do so.

The Error is specfic to `usehooks-ts 2.11.0`

![image](https://github.com/juliencrn/usehooks-ts/assets/130567419/c617d04f-5a7e-4642-86b5-5cd343e72b8e)

### To Reproduce

1. Create new Next.js App with defaults
2. Install `usehooks-ts 2.11.0`
3. Try to use `useInterval` hook in a client component

### Expected behavior

It should work as it did in previous versions, also the error comes from `useDebounceCallback` which I am not even importing.

**Comment by BlankParticle** [comment]
I did check for similar issues like #453, but the problem is we are not even using `useDebounceCallback`, so there shouldn't be any reason to install `lodash.debounce`.

I also found a fix that works for now, but shouldn't be used
in `next.config.js` we can set `experimental.optimizePackageImports` to `["usehooks-ts"]` to resolve this.

**Comment by juliencrn** [comment]
> I did check for similar issues like #453

👍

> but the problem is we are not even using `useDebounceCallback`, so there shouldn't be any reason to install `lodash.debounce`.

Indeed, this is a problem, I'm able to reproduce it, and I'll work on it today. Thanks for the bug report!

**Comment by timlindsk** [comment]
useOnClickOutside also seem to use useDebounceCallback, I get the same issue.

**Comment by BlankParticle** [comment]
> > I did check for similar issues like #453
> 
> 👍
> 
> > but the problem is we are not even using `useDebounceCallback`, so there shouldn't be any reason to install `lodash.debounce`.
> 
> Indeed, this is a problem, I'm able to reproduce it, and I'll work on it today. Thanks for the bug report!

The best thing you can do is to just include `lodash.debounce` as a normal dependency. It's less than a 1kb gziped and gets treeshaken if not used anyways.

**Comment by juliencrn** [comment]
Thanks @BlankParticle!

It's a temporary fix btw, indeed lodash.debounce is very small, but, I'd be happy to make it work to be able to release more hooks with deps (useDebounce using lodash.debounce, useCookie using cookie-js etc)

If someone wants to work on it, it's more than welcome!
