### ISSUE TITLE
Allow react 16

### ISSUE THREAD

**Issue by soullivaneuh** [juliencrn/usehooks-ts#46]
Hi,

I know this is not really a good practice to allow an old release of a vendor dependency, but as described on the official [blog posts](https://reactjs.org/blog/2020/10/20/react-v17.html#no-new-features), react 17 does not has "real breaking change" as it's a preparation state for react 18.

For now, many libraries and popular react ecosystem tools looks "not ready" to react 17, according to the NPM numerous conflict issues.

Allowing react 16 will allow more integration of your library during this period without the dependencies conflict problematic.
Plus, no code adaption should be required, but I can not be 100% sure at this point.

May you consider this request?

Regards

**Comment by juliencrn** [comment]
Hi @soullivaneuh, that makes sense, will do it now. Thanks! 👍

**Comment by juliencrn** [comment]
`usehooks-ts@1.0.8` now requires at least `react@16.8.0`.
