### ISSUE TITLE
[FEAT]: Implement optional peerDependencies

### ISSUE THREAD

**Issue by juliencrn** [juliencrn/usehooks-ts#460]
Hi everyone, 

I would like to implement optional peer dependencies to allow some hooks to have dependencies without having to install it globally. By example:

- `useDebounceCallback` requires `lodash.debounce`
- `useCookie` may requires `js-cookie`
- Etc

If I only use `useUnmount`, by example,, I don't want to have either `lodash.debounce` or `js-cookie` in my bundle.

I tried to implement this in #443 using: 

```json
 "peerDependencies": {
     "lodash.debounce": "^4",
   },
   "peerDependenciesMeta": {
     "lodash.debounce": {
       "optional": true
     }
   },
```

But it does not work as expected as it requires `lodash.debounce` anyway, even if you're not importing `useDebounce***` (like mentioned here: #458, #452, #453).

If someone knows how to fix this, it's more than welcome!

**Comment by juliencrn** [comment]
![Screenshot 2024-02-01 at 17 05 32](https://github.com/juliencrn/usehooks-ts/assets/14028029/1b46c297-95f2-4e98-bd23-a513e12962e0)

Tree-shaking looks to do the work... but bundlephobia tells us another story (2.12.0 added `lodash.debounce`)

https://bundlephobia.com/package/usehooks-ts@2.12.1

**Comment by BlankParticle** [comment]
So, I looked into this matter and found some interesting behaviours.
Most modern bundlers like vite, webpack/turbopack [bundles the entire package](https://vitejs.dev/guide/dep-pre-bundling.html) before hand to use in development.

There is a setting is Next.js/Webpack that can be used to stop this and import part of code during development but that is out of scope as the user need to manually change some config. And there is no simillar setting in vite.

Now, I am sure, If I spend enough time with all this stuff I can write a dynamic dependency import mechanism. But the overhead of that overhead would be greater that having it as the way it is.

I don't know how bundlephobia works, but I am sure that all modern bundlers can treeshake every last byte of code that is not needed.

So if we even have one dependency per hook, it would be just a development overhead and no extra code would be present in the production build. So I think we can just keep the package as it is and don't bother about this.

If you have other concerns, I would be happy to help.

**Comment by juliencrn** [comment]
I also think that we can trust modern bundlers. Thanks for your work 👍
