### ISSUE TITLE
Error when running build [BUG]

### ISSUE THREAD

**Issue by salmanfazal01** [juliencrn/usehooks-ts#475]
### Describe the bug

Since 3 days ago, I have been encountering this error when running an build on my react app:

```
Creating an optimized production build...
Failed to compile.

./node_modules/usehooks-ts/dist/index.mjs
Can't import the named export 'useCallback' from non EcmaScript module (only default export is available)
```

I am unsure whether the error is coming from my end or not because downgrading the package still gives me the same error. I have been using this library for several months now but this is new.

### To Reproduce

Install package on React 17 then build the app

### Expected behavior

Successful build

**Comment by juliencrn** [comment]
Hi @salmanfazal01,

Can you provide a minimal reproduction? 
I've tested `usehooks-ts@2.13.0` with `vite` using React 17, and it builds without any errors.
Also try to remove the `node_modules` after updating the deps, it sometimes helps

**Comment by juliencrn** [comment]
I'll close this, feel free to re-open (with more information) if the problem persists
