### ISSUE TITLE
Future of `.all-contributorsrc`

### ISSUE THREAD

**Issue by BlankParticle** [juliencrn/usehooks-ts#476]
### Describe the problem

The project is using `all-contributor` to showcase the contributors, but it hasn't been updated in 2 years. Many people are not credited and many users have become unknown (maybe due to account deletion or change of username).

![image](https://github.com/juliencrn/usehooks-ts/assets/130567419/60e52197-94ac-4808-b586-abb3a337e91c)

So What do you want to do going forward. Here are the options we have,
1. Remove the section and relevent files/deps
2. Update the `.all-contributorsrc` with proper details and remember to update it everytime someone new contributes to the project
3. Ignore it 

### Additional context

It is not important, but it feels wrong to just keep it that way

**Comment by juliencrn** [comment]
It's on my todo list, using built-in GitHub contributors is simpler to maintain as it's fully automatic, but it only includes people that have committed something, it's incomplete to me. On the other hand, `all-contributor` lets us credit anyone who helped in any way, that sounds better but I have to do it manually (for the past) and then set up a bot to smooth the process for the future. It's why I added `(#id by @user)` in the changelog and release notes, to find them quickly. 
We will do it, people spend time for free in open source, credit them is the minimal 💚

I'll let this issue open until the `.all-contributor` list is updated. Thanks for caring about this
