### ISSUE TITLE
useIsClient mentions useSSR link which goes to 404 

### ISSUE THREAD

**Issue by wachulski** [juliencrn/usehooks-ts#485]
### Describe the problem

https://github.com/juliencrn/usehooks-ts/blob/4456e32fd538daecfd67f1f47857081a7147e1c4/packages/usehooks-ts/src/useIsClient/useIsClient.md?plain=1#L3

and the link is broken. The useSSR hooks is deprecated.

**Comment by juliencrn** [comment]
Hi @wachulski, good catch, I removed the link since `useSsr` has been deprecated, thanks!
