### ISSUE TITLE
[BUG]useOnClickOutside cant use the array of ref

### ISSUE THREAD

**Issue by TENDOUZHI** [juliencrn/usehooks-ts#486]
### Describe the bug

![image](https://github.com/juliencrn/usehooks-ts/assets/82806526/a621f5aa-bba6-427b-bbda-e1d3cb198a84)
as we can see in the pic, we should use an array of ref to control the useOnClickOutside hook, but when I use it in my program, I found it doesn' t work

### To Reproduce

declare two ref
and use them in the useOnClickOutside
![image](https://github.com/juliencrn/usehooks-ts/assets/82806526/d3814eaa-5b43-4e7e-8d05-fdbf71bd82f5)

### Expected behavior

I hope someone can help me to solve the problem

**Comment by yeasin-2002** [comment]
### Not a bug 
It's not a bug, I tested on my local machine and it works fine.  

### source code


```

import { useRef } from 'react';
import { useOnClickOutside } from 'usehooks-ts';

const App = () => {
  const ref = useRef(null);
  const secondRef = useRef(null);

  const handleClickOutside = () => {
    console.log('clicked outside');
  };

  useOnClickOutside([ref, secondRef], handleClickOutside);

  return (
    <div className="grid min-h-screen justify-center   bg-gray-900 text-white ">
      <div className="flex  items-center gap-x-3">
        <button
          ref={ref}
          className=" rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
        >
          Click me
        </button>

        <button
          ref={secondRef}
          className=" rounded bg-rose-500 px-4 py-2 font-bold text-white hover:bg-rose-700"
        >
          an other button
        </button>
      </div>

      <button className=" h-12 w-40 rounded bg-green-500 px-4 py-2 font-bold text-white hover:bg-green-700">
        Outside
      </button>
    </div>
  );
};

export default App;

```

**Comment by chaad98** [comment]
> Hey [@TENDOUZHI](https://github.com/TENDOUZHI)
> 
> It's not a bug, I tested on my local machine and it works fine.
> 
> ### source code
> ```
> 
> import { useRef } from 'react';
> import { useOnClickOutside } from 'usehooks-ts';
> 
> const App = () => {
>   const ref = useRef(null);
>   const secondRef = useRef(null);
> 
>   const handleClickOutside = () => {
>     console.log('clicked outside');
>   };
> 
>   useOnClickOutside([ref, secondRef], handleClickOutside);
> 
>   return (
>     <div className="grid min-h-screen justify-center   bg-gray-900 text-white ">
>       <div className="flex  items-center gap-x-3">
>         <button
>           ref={ref}
>           className=" rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
>         >
>           Click me
>         </button>
> 
>         <button
>           ref={secondRef}
>           className=" rounded bg-rose-500 px-4 py-2 font-bold text-white hover:bg-rose-700"
>         >
>           an other button
>         </button>
>       </div>
> 
>       <button className=" h-12 w-40 rounded bg-green-500 px-4 py-2 font-bold text-white hover:bg-green-700">
>         Outside
>       </button>
>     </div>
>   );
> };
> 
> export default App;
> ```

Hi @yeasin2002,

Appreciate your response!

I actually ran into the same issue — got a red squiggly error from TypeScript. I tried following your example at first, but still hit the same problem. After some digging through forums and docs, I realized it might be due to my setup (React 19). So I had to install usehooks-ts using:
`npm i usehooks-ts --legacy-peer-deps`

Also, I solved the type error by using a non-null assertion:
`const ref = useRef(null!);`

That told TypeScript the ref wouldn’t be null at runtime, and it worked fine with useOnClickOutside.

Just sharing in case anyone else runs into similar setup issues!
