### ISSUE TITLE
[BUG] `useResizeObserver` mutate initialSize globally

### ISSUE THREAD

**Issue by Yurchishin** [juliencrn/usehooks-ts#505]
### Describe the bug

If we have an array of items, then the first item will have empty initial values `{ width: undefined, height: undefined }`, and the next one will have the initial values of the first item.

### To Reproduce

Create a list of same items that use `useResizeObserver` hook

### Expected behavior

Fix: assign `previousSize` immutable

https://github.com/juliencrn/usehooks-ts/blob/e807ab3bc9b26da3c3ee685e2c495f45c84a5d58/packages/usehooks-ts/src/useResizeObserver/useResizeObserver.ts#L60 

### Additional context

My obscure logs if that helps:

<img width="726" alt="Screenshot 2024-02-22 at 19 24 39" src="https://github.com/juliencrn/usehooks-ts/assets/36650915/215dd6e0-9c67-407a-aed0-32c8569e78b5">

**Comment by Yurchishin** [comment]
https://www.npmjs.com/package/use-resize-observer - temporary solution

**Comment by Yurchishin** [comment]
https://github.com/juliencrn/usehooks-ts/pull/504 - PR with fix already exists))

**Comment by juliencrn** [comment]
Thank you @Yurchishin, fixed by #504 indeed
