### ISSUE TITLE
[BUG] useLocalStorage hook's option param is missing

### ISSUE THREAD

**Issue by AlisonYoon** [juliencrn/usehooks-ts#517]
### Describe the bug

When trying to pass `false` to UseLocalStorageOptions's `initializeWithValue`, typescript throws an error that it can only accepts 2 arguments. 

<img width="737" alt="image" src="https://github.com/juliencrn/usehooks-ts/assets/15139653/50784105-bb91-418e-aab4-ceace3f974d7">

When checking the node_module, I see that there's no "option" param included in the first place.
```
declare function useLocalStorage<T>(key: string, initialValue: T): [T, SetValue<T>];
```

This is misleading as it's not the same as what the [documentation](https://usehooks-ts.com/react-hook/use-local-storage) is describing. 

### To Reproduce

Import `useLocalStorage` hook.
Pass key, initialValue, and options as arguments. (Following the [documentation](https://usehooks-ts.com/react-hook/use-local-storage))
You can see the error in the third argument.

### Expected behavior

`useLocalStorage` hook should accept the third argument "option" and it should work as described in the documentation.
As such:

```
useLocalStorage('key', initialValue, {
initializeWithValue: false
})
```

**Comment by juliencrn** [comment]
Hi @AlisonYoon,
Please update `usehooks-ts` and it will work.
