### ISSUE TITLE
Examples first, then API docs

### ISSUE THREAD

**Issue by jcbhmr** [juliencrn/usehooks-ts#538]
### Describe the problem

When viewing a page like https://usehooks-ts.com/react-hook/use-isomorphic-layout-effect my eyes are searching for that juicy colored code snippet that I can read and understand roughly what this hook is supposed to do and how I might use it in my code. On a longer page like https://usehooks-ts.com/react-hook/use-resize-observer with all the API docs at the top I am forced to remember 🧠💡 that "Oh! I should scroll down to see _if there is perchance_ an example block that I can read".

The ideal solution is to move the example blocks to the top as the highlight of the page. They are the most colorful and interesting part of the documentation and I believe that they should be more prominently highlighted instead of stuck below the fold.

Example from https://usehooks-ts.com/react-hook/use-resize-observer

![image](https://github.com/juliencrn/usehooks-ts/assets/61068799/8588bfaa-6d0f-4238-8ccc-63d0e338db52)

vs

![image](https://github.com/juliencrn/usehooks-ts/assets/61068799/54af4c86-11c6-41ff-953e-f0e24991da61)

If you're using VitePress or some other component that has the feature I'd also recommend using line highlights to point out the `useResizeObserver()` or similar hook in the code so that your eyes can jump straight to that instead of reading the entire ~50 line example when the example goes beyond ~25 lines or so. Like this:

![image](https://github.com/juliencrn/usehooks-ts/assets/61068799/bcbade8c-b5cc-45a0-83f2-f12615d5bae1)

For smaller examples like https://usehooks-ts.com/react-hook/use-hover the need for the hook usage itself to be highlighted is less so due to the shorter code.

**Comment by juliencrn** [comment]
Good point 👍
