### ISSUE TITLE
[BUG] useDebounceCallback has strange behavior

### ISSUE THREAD

**Issue by Floriferous** [juliencrn/usehooks-ts#634]
### Describe the bug

I encountered a strange behavior of `useDebounceCallback`, and I'm really unsure about what's going on. Essentially, all calls to the debounced function go through, but with the delay set as the second argument.

Maybe there's something basic going on that I don't understand.

### To Reproduce

To see it happen, try out this [codesandbox](https://codesandbox.io/p/sandbox/admiring-marco-fsw65p?file=%2Fsrc%2FApp.tsx).

### Expected behavior

I expect that when you type in the input quickly enough and then stop typing, the debounced function is only called once.

**Comment by autumnwoodberry** [comment]
The codesandbox link appears to be to an empty template with no example.

**Comment by Floriferous** [comment]
Oh my bad with the codesandbox, I updated the link. Thanks for looking into it :)

You're right, proper memoization fixes the issue!

**Comment by irian-codes** [comment]
Thank you @autumnwoodberry, you helped me solve my issue to! 💫

**Comment by szamanr** [comment]
i would expect the hook to handle this for me under the hood. or at least make it very clear in the documentation.

**Comment by decanTyme** [comment]
Can we reopen this? I was also having this issue before and I was forced to make a workaround. Now I'm on latest and this still isn't fixed, or at the very least still not mentioned in the docs. Right now it behaves more like a throttle without the whole memoization.

**Comment by wnadurski** [comment]
This hook doesn't work as expected, here is codesandbox to reproduce issues: https://codesandbox.io/p/sandbox/3jgy85

Two things don't work properly:
- isPending doesn't behave correctly. If you initially enter the page, this flag is "false", but if you rerender a component, without invoking the debounced function, it's changed to "true"
- The debounced function is invoked even if component using it was unmounted, which shouldn't happen

**Comment by umanghome** [comment]
https://github.com/juliencrn/usehooks-ts/pull/720 should fix it, I think
