### ISSUE TITLE
Dark mode: weird behaviour on site

### ISSUE THREAD

**Issue by ducktordanny** [juliencrn/usehooks-ts#67]
## Description

A few times I've already discovered that when I'm going to the side and I'm switching between dark mode and light mode it has some issues. Sometimes when I click the button on the navigation it's only changing a particular part of the site or not even doing anything.

## Checked

I've already checked if it's happening on localhost, but there I didn't face this problem. **It's quite weird for me that it's only happening in production.** Maybe someone else could also take a look at what've I found.

## Details

When I found this bug I was using Google Chrome, but I also noticed it on phone. I made a short video to illustrate it.

https://user-images.githubusercontent.com/38068717/143483904-a1b83ab4-bc51-4eab-9ba4-78fe5ac53b03.mov

**Comment by juliencrn** [comment]
Hello @ducktordanny, indeed weird... Thank you for the bug report ! 👍
