### ISSUE TITLE
useDarkMode Next.js issue

### ISSUE THREAD

**Issue by emulienfou** [juliencrn/usehooks-ts#84]
When using the hook `useDarkMode` and I presume it could be the same issue for other hooks with **Next.js framework** and **Material-UI**, I get the error message: `Prop className did not match.`

> In the console log, the error refer to the documentation: https://nextjs.org/docs/messages/react-hydration-error

Here is my current code generating this error:
```js
const { isDarkMode } = useDarkMode()

const theme = useMemo(
    () =>
      createTheme(themeOptions(isDarkMode ? 'dark' : 'light')),
    [isDarkMode]
  )
```

The way I was able to fix this error to happen was changing my code to:
```js
  const [dark, setDark] = useState(false)
  const { isDarkMode } = useDarkMode()

  useEffect(() => {
    setDark(isDarkMode)
  }, [isDarkMode])

  const theme = useMemo(
    () =>
      createTheme(themeOptions(dark ? 'dark' : 'light')),
    [dark]
  )
```

I do not know if this error is actually related to the hooks or maybe with the `useMemo` hook instead!

**Comment by juliencrn** [comment]
Hi @emulienfou, 

Instead (re-)creating the whole theme in the component, why not create both themes once, then use the hook's value to read the wanted version?

```js
const themes = {
  dark: createTheme(themeOptions("dark")),
  light: createTheme(themeOptions("light")),
}

function App() {
  const { isDarkMode } = useDarkMode()
  const theme = themes[isDarkMode ? "dark" : "light"]

  return (
    <Provider theme={theme}>
      ...
    </Provider>
  )
}
```

Additionally, as you can see on the [`useDarkMode()`](https://usehooks-ts.com/react-hook/use-dark-mode), the logic to handle the theme state is already implemented in the hook. Thus, you can remove these lines: 

```js
const [dark, setDark] = useState(false)

useEffect(() => {
  setDark(isDarkMode)
}, [isDarkMode])
```

**Comment by emulienfou** [comment]
@juliencrn Thanks for your answer, however I cannot apply what you're suggesting, otherwise I'm back having the behavior and error message:

```Warning: Prop `className` did not match. Server: "MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButtonBase-root css-iqmgqt-MuiButtonBase-root-MuiButton-root" Client: "MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButtonBase-root css-p43gam-MuiButtonBase-root-MuiButton-root"```

> Theme override doesnt work on MUI when having this error!

**Comment by PabloLION** [comment]
I second @emulienfou . I was using MUI too and I thought my problem was from SSR. I didn't dig very deep into it. Let's hope someone knows how to fix this.

**Comment by juliencrn** [comment]
We can't read `localStorage` and `mediaQueries` window API on SSR, it isn't an easy problem. You can try to set an arbitrary default theme mode, then, updating it during the hydration, or ensure that the `ThemeProvider` in mounted in client-side only code. 

@emulienfou, Could you create a minimal reproduction of the bug to play with it?

**Comment by ptrkcsk** [comment]
having the same issue. here's a reproduction : https://replit.com/@ptrkcsk/useDarkMode-Nextjs

**Comment by ptrkcsk** [comment]
this is how i've the solved the problem for myself using @juliencrn 's advice :

> You can try to set an arbitrary default theme mode, then, updating it during the hydration

```tsx
import { useEffect, useState } from "react";
import { useMediaQuery } from "usehooks-ts";

export default function useDarkMode(): { isDarkMode: boolean } {
  const prefersDark = useMediaQuery("(prefers-color-scheme: dark)");

  // set initial state to arbitrary default (`false`), which will be used for
  // first server render and first client render
  const [isDarkMode, setIsDarkMode] = useState<boolean>(false);

  // update on second client render
  useEffect(() => setIsDarkMode(prefersDark), []);
  // update when user preference changes
  useEffect(() => setIsDarkMode(prefersDark), [prefersDark]);

  return { isDarkMode };
}
```
