### ISSUE TITLE
Add `useSessionStorage` hook to complement `useLocalStorage`

### ISSUE THREAD

**Issue by docmars** [juliencrn/usehooks-ts#85]
Hi there! Really impressed by this collection of hooks, nice work, and thanks for sharing!

I'd love to see a `useSessionStorage` hook alongside `useLocalStorage` and wanted to add a note here to add one. If I get time I may PR one, but no promises :)

I couldn't find any well-supported hooks that support local and session storage both, but your `useLocalStorage` hook seems like one of the more solid ones.

Thank you 🎉

**Comment by juliencrn** [comment]
Hi and thank you so much, Andy! 😀

Yes, I think it is a good idea! If you want to do it, feel free, else I will do it sooner 👍

**Comment by createdbymahmood** [comment]
I'll take this.
