### ISSUE TITLE
Mistake in Documentation Page

### ISSUE THREAD

**Issue by AjayTheWizard** [juliencrn/usehooks-ts#87]
I found a mistake in Documentation in `https://usehooks-ts.com/react-hook/use-fetch`.

Where I found a `a` tag with wrong `href` attribute.
`Line 4` in `useLocalStorage()` link is `https://usehooks-ts.com/react-hook/use-fetch` instead of
`https://usehooks-ts.com/react-hooks/use-fetch`. Change `/react-hook/` as `/react-hooks/`.

**Comment by juliencrn** [comment]
Hi @AjayTheWizard,
Oh yes, good catch! Thanks 👍
