### ISSUE TITLE
CRA5 source map warning

### ISSUE THREAD

**Issue by PabloLION** [juliencrn/usehooks-ts#88]
Hi team.
I'm getting this error with create-react-app 5.0 for all hooks. 

```
WARNING in ./node_modules/usehooks-ts/esm/useWindowSize/useWindowSize.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '$REPO_ROOT/node_modules/usehooks-ts/src/useWindowSize/useWindowSize.ts' file: Error: ENOENT: no such file or directory, open '$REPO_ROOT/node_modules/usehooks-ts/src/useWindowSize/useWindowSize.ts'
```

And it has been complained a lot here: 
https://github.com/facebook/create-react-app/discussions/11767

Should we add some source map support?

**Comment by juliencrn** [comment]
Hi @PabloLION, interesting, thanks for the report, we will check it asap.

**Comment by juliencrn** [comment]
This is fixed, available on `usehooks-ts@2.2.2` 🎉
Thanks, @PabloLION for the bug report! 👍

**Comment by brightsider** [comment]
This happens again :(

**Comment by PabloLION** [comment]
Maybe we should @juliencrn

**Comment by juliencrn** [comment]
Source-map have been removed in usehooks-ts@2.7.1 (https://github.com/juliencrn/usehooks-ts/releases/tag/usehooks-ts%402.7.1). Thanks for reminding :)
