### ISSUE TITLE
useIntersectionObserver unexpected token

### ISSUE THREAD

**Issue by jeanlucmongrain** [juliencrn/usehooks-ts#93]
I'm running 2.0.2 just fine and when I upgrad eto 2.2.2:

```
./node_modules/usehooks-ts/dist/esm/useIntersectionObserver/useIntersectionObserver.js 11:23
Module parse failed: Unexpected token (11:23)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   } = _ref;
|   const [entry, setEntry] = useState();
>   const frozen = entry?.isIntersecting && freezeOnceVisible;
| 
|   const updateEntry = _ref2 => {
```

**Comment by jeanlucmongrain** [comment]
`rm -rf node_modules` fixed that

**Comment by juliencrn** [comment]
Thanks @jeanlucmongrain :)

**Comment by arusak** [comment]
I use react-scripts@4.0.3 and have the same error message. Removing node_modules didn't work for me.
I've done a bit of investigation, and found a few solutions.

1. Update react-scripts to version 5.
2. Downgrade usehooks-ts to version 2.1.1
3. Add babel plugins `proposal-optional-chaining` and `proposal-nullish-coalescing-operator` into your babel config.

I use craco to tune my build, here's the config to satisfy babel:

```
module.exports = {
  babel: {
    // need this for usehooks-ts with react-scripts@4
    plugins: [
      ['@babel/plugin-proposal-optional-chaining'],
      ['@babel/plugin-proposal-nullish-coalescing-operator'],
    ],
  }
}
```

**Comment by juliencrn** [comment]
Thanks @arusak!
